name: Publish to DockerHub
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'OpenVSCode Server release tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and publish Docker image
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Set Version and Quality
        run: |
          echo "VERSION=$(echo ${{ github.event.inputs.release_tag }} | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')" >> $GITHUB_ENV        
          quality=$([[ ${{ github.event.inputs.release_tag }} =~ nightly ]] && echo "nightly" || echo "stable")
          echo "QUALITY=$quality" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            registry.gitlab.com/ajhalili2006-experiments/images-hub/openvscode-server-dev:nightly
          tags: |
            type=semver,pattern={{version}},value=v${{ env.VERSION }},enable=${{ env.QUALITY == 'stable' }}
            type=raw,value=nightly,enable=${{ env.QUALITY == 'nightly' }}
      
      - name: Login to GLCR SaaS
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GLCR_USERNAME }}
          password: ${{ secrets.GLCR_TOKEN }}
          registry: registry.gitlab.com
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            RELEASE_TAG=${{ github.event.inputs.release_tag }}
            REPO_PATH=ajhalili2006/gitpodified-server
          tags: ${{ steps.meta.outputs.tags }}
